Refactoring
Signed-off-by: haoadoreorange <github@h4o.dev>

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,29 +1,26 @@
 #!/bin/sh
+set -eu
 
-if [ -f ".sig" ]; then
-    (
-        RED='\033[0;31m'
-        NC='\033[0m' # No Color
-        . "$(pwd)"/.sig
-        if [ -n "${name-}" ] && [ "$GIT_AUTHOR_NAME" != "$name" ]; then
-            wrong_name=true
-            wrong=true
-        fi
-        if [ -n "${email-}" ] && [ "$GIT_AUTHOR_EMAIL" != "$email" ]; then
-            wrong_email=true
-            wrong=true
-        fi
-        if [ "${wrong-}" = "true" ]; then
-            if [ "${wrong_name-}" = "true" ]; then
-                echo "${RED}Required author name for this repo: ${name}${NC}"
-            fi
-            if [ "${wrong_email-}" = "true" ]; then
-                echo "${RED}Required author email for this repo: ${email}${NC}"
-            fi
-            git config --global user.name "$name" &&
-                git config --global user.email "$email" &&
-                echo "${RED}Configured git signature accordingly, please re-commit${NC}"
-            exit 1
-        fi
-    ) || exit 1
+if [ -f .sig ]; then
+    RED='\033[0;31m'
+    NC='\033[0m' # No Color
+
+    tmp_sig=.sig.tmp
+    sed 's/ *= */=/g' .sig >"$tmp_sig"
+    . "$tmp_sig"
+    rm "$tmp_sig"
+    if [ -n "${name-}" ] && [ "$GIT_AUTHOR_NAME" != "$name" ]; then
+        echo "Required author name for this repo: $name"
+        git config --global user.name "$name"
+        wrong=true
+    fi
+    if [ -n "${email-}" ] && [ "$GIT_AUTHOR_EMAIL" != "$email" ]; then
+        echo "Required author email for this repo: $email"
+        git config --global user.email "$email"
+        wrong=true
+    fi
+    if [ "${wrong-}" = "true" ]; then
+        printf "${RED}Configured git signature accordingly, please re-commit${NC}\n"
+        exit 1
+    fi
 fi
